site_name: WebVirt
site_url: https://webvirt.sreejithiv.live
theme:
  features:
    - content.code.copy
  # logo: "assets/logo.png"
  # favicon: assets/favicon.png
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference  

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  generator: false

nav:
  - About: index.md
  - Prerequisites: prerequisites.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Management: management.md
  - Usage: usage.md
  - Quirks: quirks.md